In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
sample = [1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]

In [ ]:
#creating a dataframe

In [ ]:
df = pd.DataFrame(sample)

In [ ]:
df

0
0   1.13
1   1.55
2   1.43
3   0.92
4   1.25
5   1.36
6   1.32
7   0.85
8   1.07
9   1.48
10  1.20
11  1.33
12  1.18
13  1.22
14  1.29

In [15]:
df.shape

(15, 1)

In [ ]:
#standard deviation of dataframe

In [ ]:
std = df.std()

In [ ]:
std

0    0.193164
dtype: float64

In [ ]:
#mean of dataframe

In [ ]:
mean = df.mean()

In [ ]:
mean

0    1.238667
dtype: float64

In [ ]:
#confidence interval(99% ) by using normal distribution

In [17]:
df_confidence_normal = stats.norm.interval(0.99,loc=mean,scale=std)
print(df_confidence_normal)
print("Mean at 99% confidence interval is :",np.round(df_confidence_normal,4))

(array([0.74110884]), array([1.73622449]))
Mean at 99% confidence interval is : [[0.7411]
 [1.7362]]


In [ ]:
#confidence interval(99%) by using t distribution

In [18]:
df_confidence_t = stats.t.interval(0.99,14,loc=mean,scale=std)

In [19]:
print(np.round(df_confidence_t,4))

[[0.6636]
 [1.8137]]


In [ ]:
#confidence interval when population standard deviation is known

In [23]:
df_confidence_normal_population = stats.norm.interval(0.99,loc=mean,scale=0.2)

In [24]:
print(np.round(df_confidence_normal_population,4))

[[0.7235]
 [1.7538]]
